### 학습목표
 - random 서브모듈 함수를 통해 ndarray 생성하기

In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [6]:
np.random.rand(4,5,3)

array([[[0.54654695, 0.26797906, 0.18860871],
        [0.23697214, 0.56046864, 0.00660603],
        [0.87252871, 0.8658317 , 0.49660722],
        [0.64588804, 0.79247016, 0.22771831],
        [0.07496875, 0.69993139, 0.9494494 ]],

       [[0.25759738, 0.77203973, 0.69072993],
        [0.89632311, 0.59005111, 0.66020147],
        [0.48760055, 0.34155568, 0.33074686],
        [0.90735745, 0.98461482, 0.86281668],
        [0.7492161 , 0.88873433, 0.96800566]],

       [[0.14589888, 0.57661333, 0.71075407],
        [0.0786592 , 0.00409432, 0.56713101],
        [0.31608776, 0.93829367, 0.84638749],
        [0.51974623, 0.44201313, 0.20543465],
        [0.92461743, 0.55790308, 0.35975329]],

       [[0.29159496, 0.70847385, 0.90978358],
        [0.06355183, 0.65004004, 0.42059274],
        [0.927154  , 0.91068698, 0.02402457],
        [0.15182057, 0.66942018, 0.64904686],
        [0.09881923, 0.08491501, 0.4435701 ]]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [7]:
np.random.randn(3,4,2)

array([[[ 2.15693722, -0.50364626],
        [ 0.4944417 , -0.27347251],
        [ 0.43437694,  0.60950153],
        [-0.58820442, -0.33792543]],

       [[ 1.30877675,  0.87015973],
        [-0.9551526 ,  2.01150048],
        [ 1.20021111,  0.37526845],
        [ 0.32837585, -0.38834234]],

       [[-0.57850976,  1.29633455],
        [ 1.04196547, -1.10018776],
        [-1.88683049, -0.57801108],
        [ 0.68121895, -0.26251795]]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [9]:
np.random.randint(1,100,size=(3,5))

array([[98, 11, 81, 60, 32],
       [37, 41, 75, 37, 49],
       [87, 47, 39, 71, 43]])

In [10]:
np.random.randint(1,100,size=(3,))

array([53, 92, 15])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [16]:
np.random.seed(100)
np.random.randn(3,4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [17]:
np.random.choice(100, (3, 4))

array([[83,  4, 91, 59],
       [67,  7, 49, 47],
       [65, 61, 14, 55]])

In [19]:
x = np.array([1,2,3,1.5,2.6,2.9])
np.random.choice(x, size=(2,2), replace=False)

array([[1. , 2.6],
       [2.9, 3. ]])

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [21]:
np.random.uniform(1.0,3.0, size=(4,5))
np.random.randn(3,4)

array([[-0.68955061, -0.53547985,  1.52795302,  0.64720579],
       [-0.67733661, -0.2650188 ,  0.74610644, -3.13078483],
       [ 0.05962178, -0.87521111,  1.06487833, -0.57315265]])