## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [5]:
x = np.random.rand(3,3)
print(x)
x @ np.linalg.inv(x)


[[0.00217651 0.82802322 0.01707408]
 [0.87715988 0.29040104 0.1159859 ]
 [0.02927394 0.07241532 0.78605241]]


array([[ 1.00000000e+00,  4.93039881e-19, -4.55187747e-18],
       [ 2.62246559e-17,  1.00000000e+00, -1.37533387e-17],
       [ 4.98588923e-18,  1.24791037e-17,  1.00000000e+00]])

In [8]:
np.matmul(x, np.linalg.inv(x))

array([[ 1.00000000e+00,  4.93039881e-19, -4.55187747e-18],
       [ 2.62246559e-17,  1.00000000e+00, -1.37533387e-17],
       [ 4.98588923e-18,  1.24791037e-17,  1.00000000e+00]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [10]:
A = np.array([[1,1],[2,4]])
B = np.array([25,64])

x = np.linalg.solve(A,B)
print(x)

np.allclose(A@x, B)

[18.  7.]


True