## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [4]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)

print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.31673504 0.48613074 0.18499005 0.43256978 0.1271149 ]
 [0.03456676 0.84218205 0.60967692 0.02128715 0.31571348]
 [0.64579969 0.64543699 0.50051172 0.85849467 0.0626039 ]]


#### 연산 함수
 - add, substract, multiply, divide

In [5]:
np.add(x,y)

array([[ 0.31673504,  1.48613074,  2.18499005,  3.43256978,  4.1271149 ],
       [ 5.03456676,  6.84218205,  7.60967692,  8.02128715,  9.31571348],
       [10.64579969, 11.64543699, 12.50051172, 13.85849467, 14.0626039 ]])

In [6]:
x+y

array([[ 0.31673504,  1.48613074,  2.18499005,  3.43256978,  4.1271149 ],
       [ 5.03456676,  6.84218205,  7.60967692,  8.02128715,  9.31571348],
       [10.64579969, 11.64543699, 12.50051172, 13.85849467, 14.0626039 ]])

In [7]:
x-y

array([[-0.31673504,  0.51386926,  1.81500995,  2.56743022,  3.8728851 ],
       [ 4.96543324,  5.15781795,  6.39032308,  7.97871285,  8.68428652],
       [ 9.35420031, 10.35456301, 11.49948828, 12.14150533, 13.9373961 ]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [8]:
print(y)

[[0.31673504 0.48613074 0.18499005 0.43256978 0.1271149 ]
 [0.03456676 0.84218205 0.60967692 0.02128715 0.31571348]
 [0.64579969 0.64543699 0.50051172 0.85849467 0.0626039 ]]


In [9]:
np.mean(y)

0.40558758945873685

In [10]:
np.max(y)

0.8584946701657986

In [11]:
np.argmax(y)

13

In [12]:
np.var(y), np.median(y), np.std(y)

(0.0742673964636387, 0.43256977825751897, 0.27252045145940645)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [13]:
y

array([[0.31673504, 0.48613074, 0.18499005, 0.43256978, 0.1271149 ],
       [0.03456676, 0.84218205, 0.60967692, 0.02128715, 0.31571348],
       [0.64579969, 0.64543699, 0.50051172, 0.85849467, 0.0626039 ]])

In [14]:
np.sum(y)

6.083813841881053

In [19]:
np.sum(y,axis=1)

array([1.54754051, 1.82342636, 2.71284697])

In [15]:
np.cumsum(y)

array([0.31673504, 0.80286578, 0.98785583, 1.42042561, 1.54754051,
       1.58210727, 2.42428932, 3.03396624, 3.05525339, 3.37096687,
       4.01676656, 4.66220355, 5.16271527, 6.02120994, 6.08381384])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [21]:
z = np.random.randn(10)
print(z)

[-0.24976912  0.1869809  -0.56422378 -0.40935656  0.50307147 -0.86997086
  0.79899114 -0.472485    2.50245253  1.32971358]


In [22]:
z > 0

array([False,  True, False, False,  True, False,  True, False,  True,
        True])

In [23]:
np.any(z>0)

True

In [24]:
np.all(z>0)

False

In [25]:
np.all(z!=0)

True

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [26]:
z = np.random.randn(10)
print(z)

[-0.38490557  1.73113805 -0.80848328 -0.84161789  0.17487876  0.46258995
 -0.5993092  -0.03711873  0.83443438 -1.06323112]


In [28]:
np.where(z>0, z, 0)

TypeError: where() missing 1 required positional argument: 'condition'