## 학습목표
 1. 브로드캐스팅의 이해

In [1]:
import numpy as np

#### 브로드캐스팅
  - Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    


#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

* Shape이 같은 경우의 연산

In [6]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.95709608 0.38541445 0.55208601 0.07844876 0.22037933]
 [0.83826527 0.67611444 0.71676784 0.48950364 0.97709156]
 [0.57669397 0.08420504 0.07395946 0.31771925 0.04053323]]


In [7]:
x + y

array([[ 0.95709608,  1.38541445,  2.55208601,  3.07844876,  4.22037933],
       [ 5.83826527,  6.67611444,  7.71676784,  8.48950364,  9.97709156],
       [10.57669397, 11.08420504, 12.07395946, 13.31771925, 14.04053323]])

In [9]:
x % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

* Scalar(상수)와의 연산

In [20]:
a = np.arange(12).reshape(4,3)
b = np.arange(100, 103)
c = np.arange(1000,1004)
d = b.reshape(1,3)
print(a)
print(b)
print(c)
print(d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[1000 1001 1002 1003]
[[100 101 102]]


In [15]:
a+b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

* Shape이 다른 경우 연산

In [21]:
a+d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])